#!/bin/bash
#Αθανασιάδης Σωκράτης 2547. Ηλιάδης Αντώνιος 2671.


flag=0
while [ $flag == 0 ]
do
	echo "Write a password..."
	IFS='' #we store more than one sequal spaces too!
	read -s password
	##echo "$pas"
##10
	lenght=${#password}
	##echo $len
	flag=1
	if [ $lenght -lt 10 ]; then
		echo "Password must be more than 10 characters."
		flag=0
	fi
	if [[ ! $password =~ [A-Z] ]];then
		echo "Password must include UPPERCASE letters too."
		flag=0
	fi
	if [[ ! $password =~ [a-z] ]];then
		echo "Password, password must include LOWERCASE letters too."
		flag=0
	fi
	if [[ ! $password =~ [0-9] ]]; then
		echo "Password must include NUMBERS too."
		flag=0
	fi

done
echo "Strong Password, password accepted!"
