#!/bin/bash
#Ηλιάδης Αντώνιος 2671. Αθανασιάδης Σωκράτης 2547


set title 'Ping Requests'
set ylabel 'ms'

set terminal pngcairo
set output 'pingStats.png'

set xtics rotate
set boxwidth 0.5
set style fill solid

plot 'pingTest' using 1:3:xtic(2) with boxes



